# Generated by Django 2.2.7 on 2019-11-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.CharField(max_length=20)),
                ('holdername', models.CharField(max_length=20)),
                ('validthru', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=20)),
            ],
        ),
    ]
